const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Keyboard,
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Behaviors.Flash,
		C3.Behaviors.Timer,
		C3.Plugins.Tilemap,
		C3.Behaviors.solid,
		C3.Plugins.Touch,
		C3.Behaviors.Anchor,
		C3.Plugins.Text,
		C3.Plugins.Mouse,
		C3.Behaviors.Tween,
		C3.Plugins.Audio,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Behaviors.Platform.Cnds.OnJump,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Exps.Y,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.System.Acts.RestartLayout
	];
};
self.C3_JsPropNameTable = [
	{Keyboard: 0},
	{invul: 0},
	{Platform: 0},
	{ScrollTo: 0},
	{Flash: 0},
	{Timer: 0},
	{udin: 0},
	{Solid: 0},
	{Tilemap: 0},
	{topeng1: 0},
	{materi1: 0},
	{Touch: 0},
	{CoinGO: 0},
	{Anchor: 0},
	{HUDCOIN: 0},
	{CoinNumber: 0},
	{basicSpike: 0},
	{HUDHealth: 0},
	{nomorKuis: 0},
	{kunciJawaban: 0},
	{Pointers: 0},
	{Prasasti: 0},
	{Sprite: 0},
	{Sprite2: 0},
	{materi: 0},
	{menu: 0},
	{tujuan: 0},
	{btnMenu: 0},
	{bukuKoleksiContoh: 0},
	{homeBtn: 0},
	{warnaiObj: 0},
	{nomor: 0},
	{paletWarnaBtn: 0},
	{brush: 0},
	{kuasBtn: 0},
	{penghapusBtn: 0},
	{kuas: 0},
	{penghapus: 0},
	{areaGambar: 0},
	{Mouse: 0},
	{Tween: 0},
	{blackFade: 0},
	{scale: 0},
	{ukuranBtn: 0},
	{btnUlangi: 0},
	{kuisObj: 0},
	{cek: 0},
	{opsiBtn: 0},
	{benarSalah: 0},
	{Audio: 0},
	{penutupKuis: 0},
	{scoreTxt: 0},
	{leftMobileUi: 0},
	{rightMobileUi: 0},
	{upMobileUi: 0},
	{coin: 0},
	{health: 0},
	{KunciJawaban: 0},
	{ScoreKuis: 0},
	{OnKuas: 0},
	{OnHapus: 0},
	{WarnaBrush: 0},
	{ScaleKuas: 0}
];

self.InstanceType = {
	Keyboard: class extends self.IInstance {},
	udin: class extends self.ISpriteInstance {},
	Tilemap: class extends self.ITilemapInstance {},
	topeng1: class extends self.ISpriteInstance {},
	materi1: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	CoinGO: class extends self.ISpriteInstance {},
	HUDCOIN: class extends self.ISpriteInstance {},
	CoinNumber: class extends self.ITextInstance {},
	basicSpike: class extends self.ISpriteInstance {},
	HUDHealth: class extends self.ISpriteInstance {},
	Pointers: class extends self.ISpriteInstance {},
	Prasasti: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	materi: class extends self.ISpriteInstance {},
	menu: class extends self.ISpriteInstance {},
	btnMenu: class extends self.ISpriteInstance {},
	bukuKoleksiContoh: class extends self.ISpriteInstance {},
	homeBtn: class extends self.ISpriteInstance {},
	warnaiObj: class extends self.ISpriteInstance {},
	paletWarnaBtn: class extends self.ISpriteInstance {},
	brush: class extends self.ISpriteInstance {},
	kuasBtn: class extends self.ISpriteInstance {},
	penghapusBtn: class extends self.ISpriteInstance {},
	kuas: class extends self.ISpriteInstance {},
	penghapus: class extends self.ISpriteInstance {},
	areaGambar: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	blackFade: class extends self.ISpriteInstance {},
	ukuranBtn: class extends self.ISpriteInstance {},
	btnUlangi: class extends self.ISpriteInstance {},
	kuisObj: class extends self.ISpriteInstance {},
	opsiBtn: class extends self.ISpriteInstance {},
	benarSalah: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	penutupKuis: class extends self.ISpriteInstance {},
	scoreTxt: class extends self.ITextInstance {},
	leftMobileUi: class extends self.ISpriteInstance {},
	rightMobileUi: class extends self.ISpriteInstance {},
	upMobileUi: class extends self.ISpriteInstance {}
}